### ISSUE TITLE
[MP3] Cuda error: an illegal memory access was encountered

### ISSUE THREAD

**Issue by Jbwasse2** [s-gupta/ece598sg-mps#1]
After pulling the code and running it on my computer with a GPU (python run_behavior_cloning.py --logdir LOGDIR --env_name CartPole-v2) I get the following error on line 45 of evaluation.py.
```
  File "/home/justin/Documents/class/fall2020/ece598/ece598-mps/MP3/evaluation.py", line 45, in val
    _states = torch.from_numpy(states).float().to(device)
RuntimeError: CUDA error: an illegal memory access was encountered
```
Oddly enough it does the first pass fine.

**Comment by Jbwasse2** [comment]
I think this is just a problem on my machine, I changed cuda:0 to cuda:1 in run_behavior_cloning.py on line 79 and my error went away.
